name-template:  'v$RESOLVED_VERSION'
tag-template:   'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels: [ breaking ]
  minor:
    labels: [ feature, enhancement ]
  patch:
    labels: [ fix, bug ]
  default: patch

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
change-title-escapes: '\<*_&#@`'

exclude-labels:
  - chore
  - documentation
  - help

categories:
  - title: 'ðŸ’¥ Breaking'
    labels: [ breaking ]
  - title: 'ðŸš€ Features'
    labels: [ feature, enhancement ]
  - title: 'ðŸ› Fixes'
    labels: [ fix, bug ]
  - title: 'ðŸ§° Maintenance'
    labels: [ chore ]

autolabeler:
  - label: documentation
    files:
      - '**/*.md'
    events:
      - pull_request.opened
      - pull_request.reopened
      - pull_request.synchronize

  - label: breaking
    title:
      - '/BREAKING CHANGE:/i'
    events:
      - pull_request.opened
      - pull_request.edited

template: |
  ## Changes
  $CHANGES