name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build:
        description: "Build the Docker image"
        required: true
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PLATFORMS: linux/amd64

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    if: contains(github.event.head_commit.message, '#BUILD') || github.event_name == 'workflow_dispatch'
    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Set up QEMU (for multi-architecture builds)
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      # Step 3: Set up Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      # Step 4: Login to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}

      # Step 5: Set dynamic version from date and image name
      - name: Prepare metadata
        id: meta
        run: |
          set -euo pipefail

          IMAGE_NAME="ghcr.io/$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"

          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          if [ -f VERSION ]; then
            VERSION=$(cat VERSION | tr -d '[:space:]')
          elif [ -f version/VERSION ]; then
            VERSION=$(cat version/VERSION | tr -d '[:space:]')
          else
            echo "❌ VERSION file not found!" >&2
            exit 1
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "build_date=$BUILD_DATE" >> "$GITHUB_OUTPUT"
          echo "image_name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"

      # Step 6: Build and Push Multi-Architecture Docker Image
      - name: Build and Push Multi‑Arch Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.server
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.version }}
            ${{ steps.meta.outputs.image_name }}:latest
          no-cache: true
          provenance: false
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            BUILD_DATE=${{ steps.meta.outputs.build_date }}
            GITHUB_SHA=${{ github.sha }}
            GITHUB_REPOSITORY=${{ github.repository }}